# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('id_evento', models.IntegerField(null=True, verbose_name='id_evento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('eventoPrincipal', models.CharField(max_length=200, verbose_name='evento_principal')),
                ('sigla', models.CharField(max_length=200, verbose_name='sigla')),
                ('dataEHoradeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataeHora_inicio')),
                ('palavraChave', models.CharField(max_length=200, verbose_name='palavra_chave')),
                ('logotipo', models.CharField(max_length=200, verbose_name='logotipo')),
                ('id_pessoa', models.IntegerField(verbose_name='id_pessoa')),
                ('cidade', models.CharField(max_length=200, verbose_name='cidade')),
                ('uf', models.CharField(max_length=200, verbose_name='uf')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereco')),
                ('cep', models.CharField(max_length=200, verbose_name='cep')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEHoradeInscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataeHora_inscricao')),
                ('tipoInscricao', models.CharField(max_length=200, verbose_name='tipo_inscricao')),
                ('id_pessoaFisica', models.IntegerField(verbose_name='id_pessoaFisica')),
                ('id_evento', models.IntegerField(verbose_name='id_evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProvaG1.Pessoa')),
                ('curriculo', models.CharField(max_length=200, verbose_name='curriculo')),
                ('id_artigo', models.IntegerField(null=True, verbose_name='id_artigo')),
            ],
            bases=('ProvaG1.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProvaG1.Evento')),
                ('issn', models.CharField(max_length=200, verbose_name='issn')),
            ],
            bases=('ProvaG1.evento',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProvaG1.Pessoa')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
            ],
            bases=('ProvaG1.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProvaG1.Pessoa')),
                ('cnpj', models.CharField(max_length=200, verbose_name='cnpj')),
                ('razaoSocial', models.CharField(max_length=200, verbose_name='razaoSocial')),
            ],
            bases=('ProvaG1.pessoa',),
        ),
    ]
