# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvaG1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='id_eventoCientifico',
            field=models.IntegerField(null=True, verbose_name='id_eventoCientifico'),
        ),
    ]
